name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.8']
        poetry_version: ['1.5.0']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry_version }}

    - name: Install dependencies
      run: poetry install

    - name: Lint
      run: |
        poetry run pre-commit install
        poetry run pre-commit run --all-files

    - name: Run tests with pytest
      run: poetry run pytest tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPWRITE_PROJECT_ID: ${{ vars.APPWRITE_PROJECT_ID }}
        APPWRITE_SECRET_API_KEY: ${{ secrets.APPWRITE_SECRET_API_KEY }}
        APPWRITE_DATABASE_ID: ${{ vars.APPWRITE_DATABASE_ID }}
        APPWRITE_COLLECTION_ID: ${{ vars.APPWRITE_COLLECTION_ID }}

